version: "3.7"
services:
  bitcoin-core:
    image: cryptodockerhub/bitcoin-core:latest
    container_name: bitcoin-core
    ports:
      - ${RPC_PORT}:${RPC_PORT}
    volumes:
      - ./bitcoin-${CHAIN}.conf:/data/config.conf
    env_file:
      - ../.env
    command: bitcoind -conf=/data/config.conf -printtoconsole -dnsseed=${DNSSEED:-1} -fixedseeds=${FIXEDSEEDS:-1}
    networks:
      - bitcoin
